// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DDPM_Bin
Rcpp::List DDPM_Bin(arma::vec y, arma::vec n, double hyper_gamma_shape, double hyper_gamma_scale, double proposal_phi_sd, unsigned int NBURN, unsigned int NTHIN, unsigned int NOUTSAMPLE, const int print);
RcppExport SEXP _ddp4hc_DDPM_Bin(SEXP ySEXP, SEXP nSEXP, SEXP hyper_gamma_shapeSEXP, SEXP hyper_gamma_scaleSEXP, SEXP proposal_phi_sdSEXP, SEXP NBURNSEXP, SEXP NTHINSEXP, SEXP NOUTSAMPLESEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type hyper_gamma_shape(hyper_gamma_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type hyper_gamma_scale(hyper_gamma_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type proposal_phi_sd(proposal_phi_sdSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NBURN(NBURNSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NTHIN(NTHINSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NOUTSAMPLE(NOUTSAMPLESEXP);
    Rcpp::traits::input_parameter< const int >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(DDPM_Bin(y, n, hyper_gamma_shape, hyper_gamma_scale, proposal_phi_sd, NBURN, NTHIN, NOUTSAMPLE, print));
    return rcpp_result_gen;
END_RCPP
}
// DDPM_Bin_Ca
Rcpp::List DDPM_Bin_Ca(arma::vec y, arma::vec n, double hcauchy_scale, double proposal_M_DP_sd, double proposal_phi_sd, unsigned int NBURN, unsigned int NTHIN, unsigned int NOUTSAMPLE, const int print);
RcppExport SEXP _ddp4hc_DDPM_Bin_Ca(SEXP ySEXP, SEXP nSEXP, SEXP hcauchy_scaleSEXP, SEXP proposal_M_DP_sdSEXP, SEXP proposal_phi_sdSEXP, SEXP NBURNSEXP, SEXP NTHINSEXP, SEXP NOUTSAMPLESEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type hcauchy_scale(hcauchy_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type proposal_M_DP_sd(proposal_M_DP_sdSEXP);
    Rcpp::traits::input_parameter< double >::type proposal_phi_sd(proposal_phi_sdSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NBURN(NBURNSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NTHIN(NTHINSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NOUTSAMPLE(NOUTSAMPLESEXP);
    Rcpp::traits::input_parameter< const int >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(DDPM_Bin_Ca(y, n, hcauchy_scale, proposal_M_DP_sd, proposal_phi_sd, NBURN, NTHIN, NOUTSAMPLE, print));
    return rcpp_result_gen;
END_RCPP
}
// DDPM_Linear
Rcpp::List DDPM_Linear(const arma::vec y_C, const arma::mat x_C, const arma::vec g_C, const unsigned int n_C, const arma::vec y_h, const arma::mat x_h, const arma::vec study_id_h, const arma::vec n_h, const double hyper_gamma_shape, const double hyper_gamma_scale, const double mu_beta_G0, const double tau_beta_G0, const double alpha_sigma_G0, const double beta_sigma_G0, const double proposal_phi_sd, const unsigned int NBURN, const unsigned int NTHIN, const unsigned int NOUTSAMPLE, const int print);
RcppExport SEXP _ddp4hc_DDPM_Linear(SEXP y_CSEXP, SEXP x_CSEXP, SEXP g_CSEXP, SEXP n_CSEXP, SEXP y_hSEXP, SEXP x_hSEXP, SEXP study_id_hSEXP, SEXP n_hSEXP, SEXP hyper_gamma_shapeSEXP, SEXP hyper_gamma_scaleSEXP, SEXP mu_beta_G0SEXP, SEXP tau_beta_G0SEXP, SEXP alpha_sigma_G0SEXP, SEXP beta_sigma_G0SEXP, SEXP proposal_phi_sdSEXP, SEXP NBURNSEXP, SEXP NTHINSEXP, SEXP NOUTSAMPLESEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type y_C(y_CSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x_C(x_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type g_C(g_CSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_C(n_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y_h(y_hSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x_h(x_hSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type study_id_h(study_id_hSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type n_h(n_hSEXP);
    Rcpp::traits::input_parameter< const double >::type hyper_gamma_shape(hyper_gamma_shapeSEXP);
    Rcpp::traits::input_parameter< const double >::type hyper_gamma_scale(hyper_gamma_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_beta_G0(mu_beta_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type tau_beta_G0(tau_beta_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_sigma_G0(alpha_sigma_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_sigma_G0(beta_sigma_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type proposal_phi_sd(proposal_phi_sdSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NBURN(NBURNSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NTHIN(NTHINSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NOUTSAMPLE(NOUTSAMPLESEXP);
    Rcpp::traits::input_parameter< const int >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(DDPM_Linear(y_C, x_C, g_C, n_C, y_h, x_h, study_id_h, n_h, hyper_gamma_shape, hyper_gamma_scale, mu_beta_G0, tau_beta_G0, alpha_sigma_G0, beta_sigma_G0, proposal_phi_sd, NBURN, NTHIN, NOUTSAMPLE, print));
    return rcpp_result_gen;
END_RCPP
}
// DDPM_Linear_Ca
Rcpp::List DDPM_Linear_Ca(const arma::vec y_C, const arma::mat x_C, const arma::vec g_C, const unsigned int n_C, const arma::vec y_h, const arma::mat x_h, const arma::vec study_id_h, const arma::vec n_h, const double hcauchy_scale, const double mu_beta_G0, const double tau_beta_G0, const double alpha_sigma_G0, const double beta_sigma_G0, const double proposal_phi_sd, const double proposal_M_DP_sd, const unsigned int NBURN, const unsigned int NTHIN, const unsigned int NOUTSAMPLE, const int print);
RcppExport SEXP _ddp4hc_DDPM_Linear_Ca(SEXP y_CSEXP, SEXP x_CSEXP, SEXP g_CSEXP, SEXP n_CSEXP, SEXP y_hSEXP, SEXP x_hSEXP, SEXP study_id_hSEXP, SEXP n_hSEXP, SEXP hcauchy_scaleSEXP, SEXP mu_beta_G0SEXP, SEXP tau_beta_G0SEXP, SEXP alpha_sigma_G0SEXP, SEXP beta_sigma_G0SEXP, SEXP proposal_phi_sdSEXP, SEXP proposal_M_DP_sdSEXP, SEXP NBURNSEXP, SEXP NTHINSEXP, SEXP NOUTSAMPLESEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type y_C(y_CSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x_C(x_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type g_C(g_CSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_C(n_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y_h(y_hSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x_h(x_hSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type study_id_h(study_id_hSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type n_h(n_hSEXP);
    Rcpp::traits::input_parameter< const double >::type hcauchy_scale(hcauchy_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_beta_G0(mu_beta_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type tau_beta_G0(tau_beta_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_sigma_G0(alpha_sigma_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_sigma_G0(beta_sigma_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type proposal_phi_sd(proposal_phi_sdSEXP);
    Rcpp::traits::input_parameter< const double >::type proposal_M_DP_sd(proposal_M_DP_sdSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NBURN(NBURNSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NTHIN(NTHINSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NOUTSAMPLE(NOUTSAMPLESEXP);
    Rcpp::traits::input_parameter< const int >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(DDPM_Linear_Ca(y_C, x_C, g_C, n_C, y_h, x_h, study_id_h, n_h, hcauchy_scale, mu_beta_G0, tau_beta_G0, alpha_sigma_G0, beta_sigma_G0, proposal_phi_sd, proposal_M_DP_sd, NBURN, NTHIN, NOUTSAMPLE, print));
    return rcpp_result_gen;
END_RCPP
}
// DPM_Bin
Rcpp::List DPM_Bin(arma::vec y, arma::vec n, double hyper_gamma_shape, double hyper_gamma_scale, unsigned int NBURN, unsigned int NTHIN, unsigned int NOUTSAMPLE, const int print);
RcppExport SEXP _ddp4hc_DPM_Bin(SEXP ySEXP, SEXP nSEXP, SEXP hyper_gamma_shapeSEXP, SEXP hyper_gamma_scaleSEXP, SEXP NBURNSEXP, SEXP NTHINSEXP, SEXP NOUTSAMPLESEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type hyper_gamma_shape(hyper_gamma_shapeSEXP);
    Rcpp::traits::input_parameter< double >::type hyper_gamma_scale(hyper_gamma_scaleSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NBURN(NBURNSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NTHIN(NTHINSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NOUTSAMPLE(NOUTSAMPLESEXP);
    Rcpp::traits::input_parameter< const int >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(DPM_Bin(y, n, hyper_gamma_shape, hyper_gamma_scale, NBURN, NTHIN, NOUTSAMPLE, print));
    return rcpp_result_gen;
END_RCPP
}
// DPM_Bin_Ca
Rcpp::List DPM_Bin_Ca(arma::vec y, arma::vec n, double hcauchy_scale, double proposal_M_DP_sd, unsigned int NBURN, unsigned int NTHIN, unsigned int NOUTSAMPLE, const int print);
RcppExport SEXP _ddp4hc_DPM_Bin_Ca(SEXP ySEXP, SEXP nSEXP, SEXP hcauchy_scaleSEXP, SEXP proposal_M_DP_sdSEXP, SEXP NBURNSEXP, SEXP NTHINSEXP, SEXP NOUTSAMPLESEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type hcauchy_scale(hcauchy_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type proposal_M_DP_sd(proposal_M_DP_sdSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NBURN(NBURNSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NTHIN(NTHINSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type NOUTSAMPLE(NOUTSAMPLESEXP);
    Rcpp::traits::input_parameter< const int >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(DPM_Bin_Ca(y, n, hcauchy_scale, proposal_M_DP_sd, NBURN, NTHIN, NOUTSAMPLE, print));
    return rcpp_result_gen;
END_RCPP
}
// DPM_Linear
Rcpp::List DPM_Linear(const arma::vec y_C, const arma::mat x_C, const arma::vec g_C, const unsigned int n_C, const arma::vec y_h, const arma::mat x_h, const arma::vec study_id_h, const arma::vec n_h, const double hyper_gamma_shape, const double hyper_gamma_scale, const double mu_beta_G0, const double tau_beta_G0, const double alpha_sigma_G0, const double beta_sigma_G0, const unsigned int NBURN, const unsigned int NTHIN, const unsigned int NOUTSAMPLE, const int print);
RcppExport SEXP _ddp4hc_DPM_Linear(SEXP y_CSEXP, SEXP x_CSEXP, SEXP g_CSEXP, SEXP n_CSEXP, SEXP y_hSEXP, SEXP x_hSEXP, SEXP study_id_hSEXP, SEXP n_hSEXP, SEXP hyper_gamma_shapeSEXP, SEXP hyper_gamma_scaleSEXP, SEXP mu_beta_G0SEXP, SEXP tau_beta_G0SEXP, SEXP alpha_sigma_G0SEXP, SEXP beta_sigma_G0SEXP, SEXP NBURNSEXP, SEXP NTHINSEXP, SEXP NOUTSAMPLESEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type y_C(y_CSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x_C(x_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type g_C(g_CSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_C(n_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y_h(y_hSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x_h(x_hSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type study_id_h(study_id_hSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type n_h(n_hSEXP);
    Rcpp::traits::input_parameter< const double >::type hyper_gamma_shape(hyper_gamma_shapeSEXP);
    Rcpp::traits::input_parameter< const double >::type hyper_gamma_scale(hyper_gamma_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_beta_G0(mu_beta_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type tau_beta_G0(tau_beta_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_sigma_G0(alpha_sigma_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_sigma_G0(beta_sigma_G0SEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NBURN(NBURNSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NTHIN(NTHINSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NOUTSAMPLE(NOUTSAMPLESEXP);
    Rcpp::traits::input_parameter< const int >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(DPM_Linear(y_C, x_C, g_C, n_C, y_h, x_h, study_id_h, n_h, hyper_gamma_shape, hyper_gamma_scale, mu_beta_G0, tau_beta_G0, alpha_sigma_G0, beta_sigma_G0, NBURN, NTHIN, NOUTSAMPLE, print));
    return rcpp_result_gen;
END_RCPP
}
// DPM_Linear_Ca
Rcpp::List DPM_Linear_Ca(const arma::vec y_C, const arma::mat x_C, const arma::vec g_C, const unsigned int n_C, const arma::vec y_h, const arma::mat x_h, const arma::vec study_id_h, const arma::vec n_h, const double hcauchy_scale, const double mu_beta_G0, const double tau_beta_G0, const double alpha_sigma_G0, const double beta_sigma_G0, const double proposal_M_DP_sd, const unsigned int NBURN, const unsigned int NTHIN, const unsigned int NOUTSAMPLE, const int print);
RcppExport SEXP _ddp4hc_DPM_Linear_Ca(SEXP y_CSEXP, SEXP x_CSEXP, SEXP g_CSEXP, SEXP n_CSEXP, SEXP y_hSEXP, SEXP x_hSEXP, SEXP study_id_hSEXP, SEXP n_hSEXP, SEXP hcauchy_scaleSEXP, SEXP mu_beta_G0SEXP, SEXP tau_beta_G0SEXP, SEXP alpha_sigma_G0SEXP, SEXP beta_sigma_G0SEXP, SEXP proposal_M_DP_sdSEXP, SEXP NBURNSEXP, SEXP NTHINSEXP, SEXP NOUTSAMPLESEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type y_C(y_CSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x_C(x_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type g_C(g_CSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type n_C(n_CSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y_h(y_hSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x_h(x_hSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type study_id_h(study_id_hSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type n_h(n_hSEXP);
    Rcpp::traits::input_parameter< const double >::type hcauchy_scale(hcauchy_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_beta_G0(mu_beta_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type tau_beta_G0(tau_beta_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_sigma_G0(alpha_sigma_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_sigma_G0(beta_sigma_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type proposal_M_DP_sd(proposal_M_DP_sdSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NBURN(NBURNSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NTHIN(NTHINSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NOUTSAMPLE(NOUTSAMPLESEXP);
    Rcpp::traits::input_parameter< const int >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(DPM_Linear_Ca(y_C, x_C, g_C, n_C, y_h, x_h, study_id_h, n_h, hcauchy_scale, mu_beta_G0, tau_beta_G0, alpha_sigma_G0, beta_sigma_G0, proposal_M_DP_sd, NBURN, NTHIN, NOUTSAMPLE, print));
    return rcpp_result_gen;
END_RCPP
}
// Simple_Linear
Rcpp::List Simple_Linear(const arma::vec y, const arma::mat x, const arma::vec g, const double mu_beta_G0, const double tau_beta_G0, const double alpha_sigma_G0, const double beta_sigma_G0, const unsigned int NBURN, const unsigned int NTHIN, const unsigned int NOUTSAMPLE, const int print);
RcppExport SEXP _ddp4hc_Simple_Linear(SEXP ySEXP, SEXP xSEXP, SEXP gSEXP, SEXP mu_beta_G0SEXP, SEXP tau_beta_G0SEXP, SEXP alpha_sigma_G0SEXP, SEXP beta_sigma_G0SEXP, SEXP NBURNSEXP, SEXP NTHINSEXP, SEXP NOUTSAMPLESEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type g(gSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_beta_G0(mu_beta_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type tau_beta_G0(tau_beta_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_sigma_G0(alpha_sigma_G0SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_sigma_G0(beta_sigma_G0SEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NBURN(NBURNSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NTHIN(NTHINSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type NOUTSAMPLE(NOUTSAMPLESEXP);
    Rcpp::traits::input_parameter< const int >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(Simple_Linear(y, x, g, mu_beta_G0, tau_beta_G0, alpha_sigma_G0, beta_sigma_G0, NBURN, NTHIN, NOUTSAMPLE, print));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ddp4hc_DDPM_Bin", (DL_FUNC) &_ddp4hc_DDPM_Bin, 9},
    {"_ddp4hc_DDPM_Bin_Ca", (DL_FUNC) &_ddp4hc_DDPM_Bin_Ca, 9},
    {"_ddp4hc_DDPM_Linear", (DL_FUNC) &_ddp4hc_DDPM_Linear, 19},
    {"_ddp4hc_DDPM_Linear_Ca", (DL_FUNC) &_ddp4hc_DDPM_Linear_Ca, 19},
    {"_ddp4hc_DPM_Bin", (DL_FUNC) &_ddp4hc_DPM_Bin, 8},
    {"_ddp4hc_DPM_Bin_Ca", (DL_FUNC) &_ddp4hc_DPM_Bin_Ca, 8},
    {"_ddp4hc_DPM_Linear", (DL_FUNC) &_ddp4hc_DPM_Linear, 18},
    {"_ddp4hc_DPM_Linear_Ca", (DL_FUNC) &_ddp4hc_DPM_Linear_Ca, 18},
    {"_ddp4hc_Simple_Linear", (DL_FUNC) &_ddp4hc_Simple_Linear, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_ddp4hc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
